### ISSUE TITLE
NFA to DFA conversion bug

### ISSUE THREAD

**Issue by TheReal0din** [SeeligerN/Automata-Visualizer#1]
When NFA converted to DFA, it may occur that The starting node, which has to be an endnode isn't an endnode in the converted version. (eg.: empty words can no longer be accepted.)

**Comment by SeeligerN** [comment]
Example of an Automata that doesn't get converted correctly: 
![19b88d70-8417-4db9-80d6-534d292bb93c](https://user-images.githubusercontent.com/68186866/104124330-9196cb80-5350-11eb-8f8a-a5f5bcd9eb40.jpg)
